import {
  APP_RATING_PROMPT_ICON,
  DEFAULT_RULES,
  FEEDBACK_ICON,
  POSITIVE_RATING_THRESHOLD,
  RATING_STAR_ICON,
  STORE_RATING_ICON,
} from '../constants';
import styles from '../components/styles';

const DEFAULT_CONFIG = {
  rating: {
    component: null,
    iconInBase64: APP_RATING_PROMPT_ICON,
    iconStyle: styles.appRatingPromptIcon,
    title: 'Rate Your Experience',
    titleStyle: styles.descriptionTitleText,
    subtitle: 'How would you rate your experience so far?',
    subtitleStyle: styles.descriptionSubtitleText,
    positiveRatingThreshold: POSITIVE_RATING_THRESHOLD,
    ratingIconInBase64: RATING_STAR_ICON,
    ratingIconStyle: styles.starRating,
    ratingIconFillStyle: styles.starRatingFill,
    showRateNever: false,
    positiveButtonText: 'Submit',
    positiveButtonTextStyle: styles.positiveActionText,
    neutralButtonText: 'Rate Later',
    neutralButtonTextStyle: styles.neutralActionText,
    negativeButtonText: 'Never',
    negativeButtonTextStyle: styles.negativeActionText,
  },
  feedback: {
    component: null,
    iconInBase64: FEEDBACK_ICON,
    iconStyle: styles.appRatingPromptIcon,
    title: 'Would you mind giving us your valuable feedback?',
    titleStyle: styles.descriptionTitleText,
    subtitle: '',
    subtitleStyle: styles.descriptionSubtitleText,
    feedbackInputStyle: styles.feedbackInput,
    feedbackInputPlaceholderText: 'Please provide your feedback here',
    feedbackInputLines: 10,
    feedbackInputMaxLength: 500,
    positiveButtonText: 'Submit',
    positiveButtonTextStyle: styles.positiveActionText,
    negativeButtonText: 'Cancel',
    negativeButtonTextStyle: styles.negativeActionText,
  },
  storeRatingConfirmation: {
    component: null,
    skipStage: false,
    iconInBase64: STORE_RATING_ICON,
    iconStyle: styles.appRatingPromptIcon,
    title: 'Rate us on the store',
    titleStyle: styles.descriptionTitleText,
    subtitle: 'Would you mind spending a moment to rate us on the store? Thank you.',
    subtitleStyle: styles.descriptionSubtitleText,
    showRateNever: false,
    positiveButtonText: 'Rate Now',
    positiveButtonTextStyle: styles.positiveActionText,
    neutralButtonText: 'Rate Later',
    neutralButtonTextStyle: styles.neutralActionText,
    negativeButtonText: 'Never',
    negativeButtonTextStyle: styles.negativeActionText,
  },
  rules: DEFAULT_RULES,
};

export default DEFAULT_CONFIG;
